version: '3'

services:

  web:
    build: .
    image: web
    container_name: web
    ports:
      - '5000:5000'
    command: python FlaskApp.py run -h 0.0.0.0
    volumes:
      - .:/usr/src/FlaskTemplateSite
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=Project.Server.Config.DevelopmentConfig
    depends_on:
      - redis

  worker:
    image: web
    command: python FlaskApp.py run_worker
    volumes:
      - .:/usr/src/FlaskTemplateSite
    environment:
      - APP_SETTINGS=Project.Server.Config.DevelopmentConfig
    depends_on:
      - redis

  redis:
    image: "redis:alpine"

  dashboard:
    build: ./Project/Dashboard
    image: dashboard
    container_name: dashboard
    ports:
      - '9181:9181'
    command: rq-dashboard -H redis